language: node_js
node_js: node
cache:
  directories:
  - node_modules
branches:
  only:
  - source
install:
- npm install
script:
- git config user.name "Jiaobuzuji"
- git config user.email "jiaobuzuji@163.com"
- sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
- hexo deploy
